import type { Metadata } from 'next';
import LegalPageLayout from '@/components/LegalPageLayout';

export const metadata: Metadata = {
    title: 'BTRST Token Purchaser Terms | Braintrust',
    description: 'Terms of Token Delivery for BTRST Token purchasers, covering U.S. and Non-U.S. purchasers.',
};

export default function BtrstPurchaserTerms() {
    return (
        <LegalPageLayout title="Terms of Token Delivery">

            <h2>Terms of Token Delivery (U.S. Purchasers)</h2>
            <p><em>(scroll further down for non-U.S. Purchasers)</em></p>
            <p>The BTRST Tokens (&quot;Tokens&quot;) are being delivered to you in accordance with your Seed Subscription Agreement and/or Simple Agreement for Future Tokens or Equity (as applicable, a &quot;Token Agreement&quot;). The following terms and conditions (&quot;Terms&quot;) govern your acceptance and use of the Tokens. By accepting delivery of the Tokens, you hereby confirm that you understand the Terms and expressly agree to be bound by and comply with these Terms. Capitalized terms not defined herein shall have the meanings ascribed to them in the Token Agreement.</p>

            <h3>Securities Legend</h3>
            <p>You acknowledge and agree that the Tokens will be deemed to bear the legend set forth below (in addition to any other legend required by applicable U.S. federal, state or non-U.S. securities laws or provided in any other agreement with the Braintrust Technology Foundation or its affiliates) (the &quot;Foundation&quot;):</p>
            <p>THE TOKENS HAVE NOT BEEN REGISTERED WITH THE UNITED STATES SECURITIES AND EXCHANGE COMMISSION UNDER THE SECURITIES ACT OF 1933, AS AMENDED (THE &quot;ACT&quot;) OR ANY OTHER LAW OR REGULATION IN THE UNITED STATES OR ANY OTHER JURISDICTION, AND THE FOUNDATION DOES NOT INTEND TO REGISTER THEM. THE TOKENS MAY NOT BE TRANSFERRED, PLEDGED OR HYPOTHECATED EXCEPT AS PERMITTED UNDER THE ACT AND APPLICABLE STATE AND FOREIGN SECURITIES LAWS PURSUANT TO AN EFFECTIVE REGISTRATION STATEMENT OR AN EXEMPTION THEREFROM.</p>

            <h3>Use of Wallet</h3>
            <p>You assume full responsibility and liability for any losses resulting from any intentional or unintentional misuse or your designated wallet address (your &quot;BTRST Wallet&quot;) including, without limitation, any loss resulting from designating a non-BTRST compliant wallet for the receipt of the Tokens, any unauthorized third party access to your wallet, depositing one type of digital asset to a wallet intended for another type of digital wallet, or any errors, typos or inaccuracies in providing a valid BTRST Wallet address controlled by you to the Foundation for the receipt of the Tokens. Neither the Foundation, Freelance Labs, Inc. (the &quot;Company&quot;) nor any of their affiliates assume any responsibility or liability in connection with any such errors or misuses.</p>

            <h3>Waiver of Warranties; Assumption of Risks</h3>
            <p>NEITHER THE FOUNDATION NOR THE COMPANY MAKES ANY WARRANTY WHATSOEVER WITH RESPECT TO THE TOKENS, INCLUDING ANY (i) WARRANTY OF MERCHANTABILITY; (ii) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (iii) WARRANTY OF TITLE; OR (iv) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER ARISING BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE. EXCEPT AS EXPRESSLY SET FORTH HEREIN, YOU ACKNOWLEDGE THAT (A) THE BRAINTRUST NETWORK MAY HAVE UNDERGONE SIGNIFICANT CHANGES TO ITS SPECIFICATIONS, DESIGN AND OTHER FEATURES SINCE THE DATE OF YOUR TOKEN AGREEMENT, AND YOU ARE ACCEPTING DELIVERY OF SUCH TOKENS IN SATISFACTION OF YOUR TOKEN AGREEMENT NOTWITHSTANDING ANY SUCH CHANGES, (B) YOU HAVE NOT RELIED UPON ANY REPRESENTATION OR WARRANTY MADE BY THE FOUNDATION, THE COMPANY, OR ANY OTHER PERSON ON THEIR BEHALF. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, YOU ASSUME ALL RISKS AND LIABILITIES FOR THE RESULTS OBTAINED BY THE USE OF ANY TOKENS AND REGARDLESS OF ANY ORAL OR WRITTEN STATEMENTS MADE BY THE COMPANY OR THE FOUNDATION, BY WAY OF TECHNICAL ADVICE OR OTHERWISE, RELATED TO THE USE OF THE TOKENS.</p>

            <h3>Indemnity</h3>
            <p>NEITHER THE COMPANY NOR THE FOUNDATION SHALL BE LIABLE TO YOU, AND YOU WILL INDEMNIFY, DEFEND AND HOLD HARMLESS THE COMPANY, THE FOUNDATION AND THEIR AGENTS AND ADVISORS, AND THE SUCCESSORS AND ASSIGNS OF THE FOREGOING, FROM AND AGAINST, ALL OR ANY PART OF ANY THIRD PARTY CAUSES OF ACTION, CLAIMS, LIABILITIES, LOSSES, COSTS, DAMAGES AND EXPENSES (INCLUDING, WITHOUT LIMITATION, ATTORNEYS&apos; FEES AND EXPENSES) (COLLECTIVELY &quot;CLAIMS&quot;) FOR DAMAGES TO OR LOSS OF PROPERTY ARISING OUT OF OR RESULTING FROM THE TRANSACTIONS CONTEMPLATED HEREIN, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, EXCEPT TO THE EXTENT SUCH CLAIMS ARISE FROM THE BAD FAITH OR INTENTIONAL MISCONDUCT OF THE COMPANY OR THE FOUNDATION.</p>

            <h3>Limitation of Liability</h3>
            <p>NEITHER THE COMPANY, THE FOUNDATION NOR ANY OTHER PARTY INVOLVED IN THE OFFERING WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE ACTIVITIES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH YOUR TOKEN AGREEMENT OR YOUR PARTICIPATION IN, OR INABILITY TO PARTICIPATE IN, THE OFFERING, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE FOUNDATION OR ANY OTHER PARTY HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY. IN NO EVENT WILL THE COMPANY&apos;S AND THE FOUNDATION&apos;S TOTAL LIABILITY TO YOU ARISING OUT OF OR IN CONNECTION WITH THIS TOKEN AGREEMENT OR FROM YOUR PARTICIPATION IN, OR INABILITY TO PARTICIPATE IN, THE OFFERING, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, EXCEED THE TOTAL PURCHASE PRICE IN YOUR TOKEN AGREEMENT (AS DENOMINATED IN USD). THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND THE COMPANY.</p>

            <h3>Class Action Waiver</h3>
            <p>Any claim or dispute arising under the Token Agreement or from your receipt, transfer, use or disposition of the Tokens will take place on an individual basis without resort to any form of class or representative action (the &quot;Class Action Waiver&quot;). THIS CLASS ACTION WAIVER PRECLUDES ANY PARTY FROM PARTICIPATING IN OR BEING REPRESENTED IN ANY CLASS OR REPRESENTATIVE ACTION REGARDING A CLAIM. Notwithstanding anything to the contrary, the validity and effect of this Class Action Waiver may be determined only by a court or referee and not by an arbitrator, and you acknowledge that this Class Action Waiver is material and essential to the arbitration of any disputes between the parties and is non-severable from the Token Agreement.</p>

            <h3>Consent to Conversion and Termination</h3>
            <p>To the extent you are a holder of a Simple Agreement for Future Tokens or Equity (a &quot;SAFT-E&quot;) being converted and/or cancelled in consideration of your receipt of Tokens, you hereby agree that the entire amount owed to you under such SAFT-E is being tendered in exchange for your Tokens, and effective upon your acceptance of these terms, without any further action required by you, the Company or the Foundation, such SAFT-E and all obligations set forth therein shall be immediately deemed satisfied in full and terminated in their entirety, including, but not limited to, any security interest effected therein. To the extent that you are party to a Seed Subscription Agreement, you hereby agree that upon your receipt of the Tokens, all obligations set forth therein shall be immediately deemed satisfied in full and terminated in their entirety.</p>

            <hr />

            <h2>Terms of Token Delivery (Non-U.S. Purchasers)</h2>
            <p>The BTRST Tokens (&quot;Tokens&quot;) are being delivered to you in accordance with your Seed Subscription Agreement and/or Simple Agreement for Future Tokens or Equity (as applicable, a &quot;Token Agreement&quot;). The following terms and conditions (&quot;Terms&quot;) govern your acceptance and use of the Tokens. By accepting delivery of the Tokens, you hereby confirm that you understand the Terms and expressly agree to be bound by and comply with the Terms.</p>

            <h3>Regulation S Compliance</h3>
            <p>(a) You are not a U.S. Person as defined in Rule 902(k) of Regulation S (&quot;Regulation S&quot;) under the U.S. Securities Act of 1933, as amended (the &quot;Securities Act&quot;). You understand and agree that: (i) the offer and sale of the Tokens is made in an offshore transaction (as defined in Rule 902(h) of Regulation S); (ii) no directed selling efforts (as defined in Rule 902(c) of Regulation S) were made in the United States; and (iii) you are not acquiring the Tokens for the account or benefit of any U.S. Persons.</p>
            <p>(b) You will not, (i) during the restricted period that is applicable to the Tokens set forth in the legend set forth below (the &quot;Restricted Period&quot;) and to any certificate representing the Tokens, offer or sell any Tokens (or create or maintain any derivative position equivalent thereto) in the United States, to or for the account or benefit of a U.S. Person or other than in accordance with Regulation S, or (ii) engage in hedging transactions with regard to the Tokens prior to the expiration of the Restricted Period.</p>
            <p>(c) You will, after the expiration of the applicable Restricted Period, offer, sell, pledge or otherwise transfer the Tokens (or create or maintain any derivative position equivalent thereto) only pursuant to registration under the Securities Act or any available exemption therefrom and, in any case, in accordance with applicable U.S. state securities laws.</p>
            <p>(d) You acknowledge and agree that the Tokens will be deemed to bear the legend set forth below (in addition to any other legend required by applicable U.S. federal, state or non-U.S. securities laws or provided in any other agreement with the Braintrust Technology Foundation (the &quot;Foundation&quot;) or its affiliates):</p>
            <p>THE TOKENS HAVE NOT BEEN REGISTERED UNDER THE SECURITIES ACT OF 1933, AS AMENDED (THE &quot;ACT&quot;) WITH THE UNITED STATES SECURITIES AND EXCHANGE COMMISSION, AND THE FOUNDATION DOES NOT INTEND TO REGISTER THEM. PRIOR TO THE ONE-YEAR ANNIVERSARY OF THE DATE THE TOKEN IS DELIVERED TO YOU (THE &quot;ONE-YEAR DEADLINE&quot;), THE TOKENS MAY NOT BE OFFERED OR SOLD (INCLUDING OPENING A SHORT POSITION IN SUCH TOKENS) IN THE UNITED STATES OR TO U.S. PERSONS (AS DEFINED BY RULE 902(k) ADOPTED UNDER THE ACT), OTHER THAN TO DISTRIBUTORS, UNLESS THE TOKENS ARE REGISTERED UNDER THE ACT, OR AN EXEMPTION FROM THE REGISTRATION REQUIREMENTS OF THE ACT IS AVAILABLE. PURCHASERS OF TOKENS PRIOR TO THE ONE-YEAR DEADLINE MAY RESELL SUCH TOKENS ONLY PURSUANT TO AN EXEMPTION FROM REGISTRATION UNDER THE ACT OR OTHERWISE IN ACCORDANCE WITH THE PROVISIONS OF REGULATION S OF THE ACT, OR IN TRANSACTIONS EFFECTED OUTSIDE OF THE UNITED STATES, PROVIDED, IN EACH CASE, THEY DO NOT SOLICIT (AND NO ONE ACTING ON THEIR BEHALF SOLICITS) PURCHASERS IN THE UNITED STATES OR OTHERWISE ENGAGE(S) IN SELLING EFFORTS IN THE UNITED STATES AND PROVIDED THAT HEDGING TRANSACTIONS INVOLVING THESE TOKENS MAY NOT BE CONDUCTED UNLESS IN COMPLIANCE WITH THE ACT. A HOLDER OF THE TOKENS WHO IS A DISTRIBUTOR, DEALER, SUB-UNDERWRITER OR OTHER SECURITIES PROFESSIONAL, IN ADDITION, CANNOT PRIOR TO THE ONE-YEAR DEADLINE, RESELL THE TOKENS TO A U.S. PERSON AS DEFINED BY RULE 902(k) OF REGULATIONS UNLESS THE TOKENS ARE REGISTERED UNDER THE ACT OR AN EXEMPTION FROM REGISTRATION UNDER THE ACT IS AVAILABLE.</p>

            <h3>Restricted Jurisdictions</h3>
            <p>You are not located, incorporated or otherwise established in, or a citizen or resident of any state, country or other jurisdiction that is designated by the U.S. Secretary of State as a country supporting international terrorism, or to which U.S. nationals cannot lawfully engage in transactions as designated by the Office of Foreign Assets Control (&quot;OFAC&quot;), including Cuba, Crimea region of Ukraine, Democratic People&apos;s Republic of Korea, Iran and Syria, and you are not a person found on the OFAC Specially Designated Nationals, Blocked Persons List, or any other consolidated prohibited persons list as determined by any applicable governmental authority.</p>

            <h3>Use of Wallet</h3>
            <p>You assume full responsibility and liability for any losses resulting from any intentional or unintentional misuse or your designated wallet address (your &quot;BTRST Wallet&quot;) including, without limitation, any loss resulting from designating a non-BTRST compliant wallet for the receipt of the Tokens, any unauthorized third party access to your wallet, depositing one type of digital asset to a wallet intended for another type of digital wallet, or any errors, typos or inaccuracies in providing a valid BTRST Wallet address controlled by you to the Foundation for the receipt of the Tokens. Neither the Foundation, Freelance Labs, Inc. (the &quot;Company&quot;) nor any of their affiliates assume any responsibility or liability in connection with any such errors or misuses.</p>

            <h3>Waiver of Warranties; Assumption of Risks</h3>
            <p>NEITHER THE FOUNDATION NOR THE COMPANY MAKES ANY WARRANTY WHATSOEVER WITH RESPECT TO THE TOKENS, INCLUDING ANY (i) WARRANTY OF MERCHANTABILITY; (ii) WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (iii) WARRANTY OF TITLE; OR (iv) WARRANTY AGAINST INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS OF A THIRD PARTY; WHETHER ARISING BY LAW, COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE OF TRADE, OR OTHERWISE. EXCEPT AS EXPRESSLY SET FORTH HEREIN, YOU ACKNOWLEDGE THAT (A) THE BRAINTRUST NETWORK MAY HAVE UNDERGONE SIGNIFICANT CHANGES TO ITS SPECIFICATIONS, DESIGN AND OTHER FEATURES SINCE THE DATE OF YOUR TOKEN AGREEMENT, AND YOU ARE ACCEPTING DELIVERY OF SUCH TOKENS IN SATISFACTION OF YOUR TOKEN AGREEMENT NOTWITHSTANDING ANY SUCH CHANGES, (B) YOU HAVE NOT RELIED UPON ANY REPRESENTATION OR WARRANTY MADE BY THE FOUNDATION, THE COMPANY, OR ANY OTHER PERSON ON THEIR BEHALF. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, YOU ASSUME ALL RISKS AND LIABILITIES FOR THE RESULTS OBTAINED BY THE USE OF ANY TOKENS AND REGARDLESS OF ANY ORAL OR WRITTEN STATEMENTS MADE BY THE COMPANY OR THE FOUNDATION, BY WAY OF TECHNICAL ADVICE OR OTHERWISE, RELATED TO THE USE OF THE TOKENS.</p>

            <h3>Indemnity</h3>
            <p>NEITHER THE COMPANY NOR THE FOUNDATION SHALL BE LIABLE TO YOU, AND YOU WILL INDEMNIFY, DEFEND AND HOLD HARMLESS THE COMPANY, THE FOUNDATION AND THEIR AGENTS AND ADVISORS, AND THE SUCCESSORS AND ASSIGNS OF THE FOREGOING, FROM AND AGAINST, ALL OR ANY PART OF ANY THIRD PARTY CAUSES OF ACTION, CLAIMS, LIABILITIES, LOSSES, COSTS, DAMAGES AND EXPENSES (INCLUDING, WITHOUT LIMITATION, ATTORNEYS&apos; FEES AND EXPENSES) (COLLECTIVELY &quot;CLAIMS&quot;) FOR DAMAGES TO OR LOSS OF PROPERTY ARISING OUT OF OR RESULTING FROM THE TRANSACTIONS CONTEMPLATED HEREIN, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, EXCEPT TO THE EXTENT SUCH CLAIMS ARISE FROM THE BAD FAITH OR INTENTIONAL MISCONDUCT OF THE COMPANY OR THE FOUNDATION.</p>

            <h3>Limitation of Liability</h3>
            <p>NEITHER THE COMPANY, THE FOUNDATION NOR ANY OTHER PARTY INVOLVED IN THE OFFERING WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE ACTIVITIES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH YOUR TOKEN AGREEMENT OR YOUR PARTICIPATION IN, OR INABILITY TO PARTICIPATE IN, THE OFFERING, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE FOUNDATION OR ANY OTHER PARTY HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY. IN NO EVENT WILL THE COMPANY&apos;S AND THE FOUNDATION&apos;S TOTAL LIABILITY TO YOU ARISING OUT OF OR IN CONNECTION WITH THIS TOKEN AGREEMENT OR FROM YOUR PARTICIPATION IN, OR INABILITY TO PARTICIPATE IN, THE OFFERING, INCLUDING YOUR RECEIPT, TRANSFER, USE OR DISPOSITION OF THE TOKENS, EXCEED THE TOTAL PURCHASE PRICE IN YOUR TOKEN AGREEMENT (AS DENOMINATED IN USD). THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND THE COMPANY.</p>

            <h3>Class Action Waiver</h3>
            <p>Any claim or dispute arising under the Token Agreement or from your receipt, transfer, use or disposition of the Tokens will take place on an individual basis without resort to any form of class or representative action (the &quot;Class Action Waiver&quot;). THIS CLASS ACTION WAIVER PRECLUDES ANY PARTY FROM PARTICIPATING IN OR BEING REPRESENTED IN ANY CLASS OR REPRESENTATIVE ACTION REGARDING A CLAIM. Notwithstanding anything to the contrary, the validity and effect of this Class Action Waiver may be determined only by a court or referee and not by an arbitrator, and you acknowledge that this Class Action Waiver is material and essential to the arbitration of any disputes between the parties and is non-severable from the Token Agreement.</p>

            <h3>Consent to Conversion and Termination</h3>
            <p>To the extent you are a holder of a Simple Agreement for Future Tokens or Equity (a &quot;SAFT-E&quot;) being converted and/or cancelled in consideration of your receipt of Tokens, you hereby agree that the entire amount owed to you under such SAFT-E is being tendered in exchange for your Tokens, and effective upon your acceptance of these terms, without any further action required by you, the Company or the Foundation, such SAFT-E and all obligations set forth therein shall be immediately deemed satisfied in full and terminated in their entirety, including, but not limited to, any security interest effected therein. To the extent that you are party to a Seed Subscription Agreement, you hereby agree that upon your receipt of the Tokens, all obligations set forth therein shall be immediately deemed satisfied in full and terminated in their entirety.</p>
        </LegalPageLayout>
    );
}
