import type { Metadata } from 'next';
import LegalPageLayout from '@/components/LegalPageLayout';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Privacy Policy | Braintrust',
    description: 'Braintrust Marketplace Privacy Policy. Learn how we collect, use, and protect your personal information.',
};

export default function PrivacyPolicy() {
    return (
        <LegalPageLayout title="Privacy Policy" lastUpdated="October 25, 2024">
            <p>Freelance Labs Inc. (&quot;Freelance Labs&quot;) provides this Privacy Policy to let you know our policies and procedures regarding the collection, use and disclosure of information through www.usebraintrust.com (the &quot;Site&quot;), and any other related, applications, software and services (together with the Site, the &quot;Service&quot;), as well as any information Freelance Labs collects offline in connection with the Service. It also describes the choices available to you regarding the use of, your access to, and how to update and correct your personal information. Note that we combine the information we collect from you from the Site, through the Service generally, or offline.</p>
            <p>Please note that certain features or services referenced in this Privacy Policy may not be offered on the Service at all times. Please also review our <Link href="/terms">Terms of Service</Link>, which governs your use of the Service.</p>
            <p>We&apos;ve provided short summaries in this Privacy Policy to help you understand what information we collect, how we use it, and what choices or rights you may have. While these summaries help explain some of the concepts in a simple and clear way, we encourage you to read the entire Privacy Policy to understand our data practices.</p>

            <hr />

            <h2>1. Information Collection</h2>
            <p>Users of the Service may be Clients, Freelancers, or Agencies (as each is defined in the Terms of Service).</p>

            <h3>1.1 Information You Provide to Us</h3>
            <p>When you use the Service, you may provide us with information about you. This may include your name and contact information, financial information to make or receive payment for services obtained through the Freelance Labs platform, or information to help us fill out tax forms. When you use the Service, we may also collect information related to your use of the Service and aggregate this with information about other users. This helps us improve our Services for you. You may also provide us with information about your contacts or friends if, for example, you&apos;d like to add those contacts to a message room. Agencies may also provide us with information about Freelancers associated with the Agency.</p>
            <ul>
                <li><strong>Personal Information:</strong> In the course of using the Service (whether as a Client or Freelancer), we may require or otherwise collect information that identifies you as a specific individual and can be used to contact or identify you (&quot;Personal Information&quot;). Examples of Personal Information include your name, email address, company address, billing address, and phone number.</li>
                <li><strong>Payment Information:</strong> If you use the Service to make or receive payments, we will also collect certain payment information, such as credit card, PayPal or other financial account information, and billing address.</li>
                <li><strong>Identity Verification:</strong> We may collect Personal Information, such as your date of birth or taxpayer identification number, as may be required by law, such as to complete tax filings. We may request documents to verify this information, such as a copy of your government-issued identification or photo or a billing statement.</li>
                <li><strong>Non-Identifying Information/Usernames:</strong> We also may collect other information, such as zip codes, demographic data, information regarding your use of the Service, and general project-related data (&quot;Non-Identifying Information&quot;). We may aggregate information collected from Freelance Labs registered and non-registered users (&quot;Freelance Labs Users&quot;). We consider usernames to be Non-Identifying Information. Usernames are made public through the Service and are viewable by other Freelance Labs Users.</li>
                <li>In some cases, we may render Personal Information (generally, email address) into a form of Non-Identifying Information referred to in this Privacy Policy as &quot;Hashed Information.&quot; This is typically accomplished using a mathematical process (commonly known as a hash function) to convert information into a code. The code does not identify you directly, but it may be used to connect your activity and interests.</li>
                <li><strong>Combination of Personal and Non-Identifying Information:</strong> Certain Non-Identifying Information would be considered a part of your Personal Information if it were combined with other identifiers in a way that enables you to be identified (for example, combining information with your name). But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your viewing preferences). We may combine your Personal Information with Non-Identifying Information, but Freelance Labs will treat the combined information as Personal Information.</li>
                <li><strong>Collection of Third Party Personal Information:</strong> We collect the following personal information from you about your contacts or friends: First name, last name, and email address when you provide it to us for the purpose of adding your contacts to a message room.</li>
            </ul>
            <p>You do not have a statutory obligation to provide us with any information, but you may have a contractual obligation to do so, and if we do not receive certain information from you, then we will not be able to provide our Service to you. If you have any questions regarding whether provision of information is mandatory and the consequences for withholding such information, please contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</p>

            <h3>1.2 Information Received from Third Parties</h3>
            <p>Third parties may also give us information about you. If we combine that information with information about you collected through the Service, we will still treat that combined information as set forth in this Privacy Policy.</p>
            <p>We also may receive information about you from third parties. For example, we may supplement the information we collect with outside records or third parties may provide information in connection with a co-marketing agreement or at your request (such as if you choose to sign in with a third-party service). If we combine the information we receive from others with information we collect through the Service, we will treat the combined information as described in this Privacy Policy.</p>

            <h3>1.3 Information Collected Automatically</h3>
            <p>Like other online companies, we receive technical information when you use our Services. We use these technologies to analyze how people use our Services, to improve how our Site functions, to save your log-in information for future sessions, and to serve you with advertisements that may interest you.</p>
            <p>We and our third party service providers, including analytics and third party content providers, may automatically collect certain information from you whenever you access or interact with the Service. This information may include, among other information, the browser and operating system you are using, the URL or advertisement that referred you to the Service, the search terms you entered into a search engine that led you to the Service, areas within the Service that you visited, and other information commonly shared when browsers communicate with websites. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, to improve marketing, analytics, and site functionality.</p>
            <p>The information we collect also includes the Internet Protocol (&quot;IP&quot;) address or other unique device identifier (&quot;Device Identifier&quot;) for any device (computer, mobile phone, tablet, etc.) used to access the Service. A Device Identifier is a number that is automatically assigned or connected to the device you use to access the Service, and our servers identify your device by its Device Identifier. Some mobile service providers may also provide us or our third party service providers with information regarding the physical location of the device used to access the Service.</p>
            <p>Freelance Labs and its partners use cookies or similar technologies to analyze trends, administer the website, track users&apos; movement around the website, and to gather demographic information about our user base as a whole. The technology used to collect information automatically from Freelance Labs Users may include the following:</p>
            <ul>
                <li><strong>Cookies:</strong> Like many websites, we and our marketing partners, affiliates, analytics, and service providers use &quot;cookies&quot; to collect information. A cookie is a small data file that we transfer to your computer&apos;s hard disk for record-keeping purposes. We use both persistent cookies that remain on your computer or similar device (such as to save your registration ID and login password for future logins to the Service and to track your compliance with the Freelance Labs Terms of Service) and session ID cookies, which expire at the end of your browser session (for example, to enable certain features of the Service, to better understand how Freelance Labs Users interact with the Service and to monitor aggregate usage by Freelance Labs Users and web traffic routing on the Service). You can control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functionality of the Service. For further information on cookies and how they are used for the Service, please visit our <Link href="/cookie-policy">Cookie Policy</Link>.</li>
                <li><strong>Web Beacons:</strong> We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as &quot;web beacons&quot; and/or &quot;tracking tags&quot; to help us keep track of what content on our Service is effective and to serve relevant advertising to you. Web beacons are small graphics with a unique identifier that may be invisible to you, and which are used to track the online activity of Internet users. Web beacons are embedded in the web pages you review or email messages you receive. Web beacons or similar technologies may be used for a number of purposes, including, without limitation, to count visitors to our Service, to monitor how Freelance Labs Users navigate the Service, to count how many emails that were sent were actually opened, or to count how many particular articles or links were actually viewed.</li>
                <li><strong>Embedded Scripts:</strong> We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as an Embedded Script. An Embedded Script is programming code that is designed to collect information about your interactions with the Service, such as the links you click on. The code is temporarily downloaded onto your computer or other device and is deactivated or deleted when you disconnect from the Service.</li>
            </ul>
            <p>In addition, we and our marketing partners, affiliates, analytics, and service providers may use a variety of other technologies (such as tags) that collect similar information for security and fraud detection purposes and we may use third parties to perform these services on our behalf.</p>

            <h3>1.3 How We Respond to Do Not Track Signals</h3>
            <p>Freelance Labs does not respond to, or alter its practice, when a Do-Not-Track signal is received.</p>

            <h3>1.4 User Profiles</h3>
            <p>Freelancers may create a profile, with certain or all information publicly available. Clients and Agencies may also create organization profiles.</p>
            <p>You may have the opportunity to create a profile, which consists of information about you, and may include Personal Information, photographs, examples of your work, information on work previously performed via the Service and outside the Service, skills, tests taken, test scores, hourly pay rates, feedback/rating information and other information, including your username (&quot;Profile&quot;). The information in your Profile may be visible to all Freelance Labs Users and the general public subject to the privacy choices you make within your Freelance Labs Profile. You may edit certain information in your Profile via your account and may choose to limit who is able to view certain content you post to your Profile. Clients and Agencies of associated individual users or companies may also have the opportunity to create an organization Profile. If, in any case, you believe that an unauthorized profile has been created about you, you can request for it to be removed by contacting us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</p>

            <h3>1.5 Messaging</h3>
            <p>Freelancers, Agencies, and Clients may communicate with each other through the Service. For example, Freelancers, Agencies, and Clients may wish to discuss Client needs and Freelancer work proposals. If you communicate with an Agency or Client, that Agency or Client will also be a &quot;data controller&quot; with respect to such communications.</p>

            <h3>1.6 Community Forums</h3>
            <p>We may offer public forums or blogs. If you participate, your comments and questions will be publicly displayed.</p>
            <p>The Service may provide you the opportunity to participate and post content publicly in forums, on blogs, through interactive features Freelance Labs and through other communication functionality (&quot;Community Forums&quot;). You may choose, through such features or otherwise, to submit or post questions, comments, or other content (collectively, &quot;User Forum Content&quot;). Please note that certain information, such as your name and Profile may be publicly displayed on the Service along with your User Forum Content.</p>
            <p>Note that anything you post to a Community Forum is public — others will have access to your User Forum Content and may use it or share it with third parties. If you choose to voluntarily disclose Personal Information in your User Forum Content or use Community Forums to link to your Profile, that information will be considered public information and the protections of this Privacy Policy will not apply.</p>
            <p>To request removal of your personal information from our blog or community forum, contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>. In some cases, we may not be able to remove your Personal Information, in which case we will let you know if we are unable to do so and why.</p>

            <h3>1.7 Testimonials</h3>
            <p>We display personal testimonials of satisfied customers on our Service, in addition to other endorsements. With your consent we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</p>

            <h3>1.8 Work Listings Through the Service</h3>
            <p>If you choose to post a work listing via the Service as a Client, the contents of such listing will be viewable publicly, unless you designate the listing as only viewable through the Service or as private using the settings available on the applicable website. Work listings include information such as budget, location, history of work listing(s) by the Client, the names of other Freelancers performing work for the Client, Client feedback and rating information and timing of project performance.</p>

            <h3>1.9 Feedback</h3>
            <p>We collect feedback from Freelance Labs Users about their experience with other Freelance Labs Users of our Service. Please note that any feedback you provide via the Service or feedback provided about you is publicly viewable via the Service. On very rare occasions, we may remove feedback pursuant to the relevant provisions of our Terms of Service.</p>

            <h3>2.0 Email to Friends and Referral Program</h3>
            <p>Freelance Labs lets you send project postings to friends via email. Freelance Labs also offers the ability to send friends emails about providing or purchasing services through the Service. If you choose to use either feature, your friend&apos;s email address will be used to send the requested posting and your email address will be used to copy you on the message to your friend or to send the message on your behalf. Freelance Labs stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program.</p>
            <p>Your friend may contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a> to request that we remove this information from our database.</p>

            <h3>2.1 Social Networking Services</h3>
            <p>You may register for an account directly with our Site, or through a social networking service (&quot;SNS&quot;) (e.g., Facebook, Github and other third party services that let you sign in using your existing credentials with those services). If you choose to register via an SNS, or to later link your account with the Service to your account with an SNS, we will use the Personal Information you have provided to the SNS (such as your name, email address, gender and other information you make publicly available via the SNS) to create your account. Note that the information we collect from and through an SNS may depend on the privacy settings you have set with the SNS and the permissions you grant to us in connection with linking your account with the Service to your account with an SNS.</p>
            <p>The Freelance Labs Service also may permit additional interactions between it and a third party website, service, or other content provider, such as enabling you to &quot;like&quot; or share content to a third party SNS. If you choose to &quot;like&quot; or share content, or to otherwise share information from or via our Service with a third party site or service, that information may be publicly displayed, and the third party may have access to information about you and your use of our Service. These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Your interactions with third parties through an SNS or similar features are governed by the respective privacy policies of those third parties.</p>
            <p>You can disable the link between your Freelance Labs account and your SNS account at any time though the &quot;Settings&quot; section of our Service. Please note that your relationship with any SNS is governed solely by your agreement(s) with such SNS.</p>

            <h2>2. Use of Information</h2>
            <p>We use information collected through the Service to provide and improve the Service, process your requests, prevent fraud, provide you with information and advertising that may interest you, comply with the law, and as otherwise permitted with your consent.</p>

            <h3>2.1 We Use Information We Collect:</h3>
            <ul>
                <li>To provide and improve the Service, complete your transactions, and address your inquiries, process your registration, verify the information you provide is valid, and for compliance and internal business purposes.</li>
                <li>To contact you with administrative communications and Freelance Labs newsletters, marketing or promotional materials (on behalf of Freelance Labs or third parties) and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the instructions in the Your Choices and Rights section, below.</li>
                <li>To tailor content we display to you and offers we may present to you, both on the Service and elsewhere online.</li>
                <li>To administer and develop our business relationship with you and, if applicable, the corporation or other legal entity you represent.</li>
                <li>To assess your proposal to perform a freelance project for Freelance Labs and prepare related governmental and internal statistics reports.</li>
                <li>To enforce and comply with the law, including to conduct an investigation, to protect the property and rights of Freelance Labs or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Freelance Labs Users.</li>
                <li>For the purposes disclosed at the time you provide your information, with your consent, and as further described in this Privacy Policy.</li>
            </ul>
            <p>We use your Personal Information for the purposes described above:</p>
            <ul>
                <li><strong>For Our Legitimate Interests.</strong> In many cases, we handle Personal Information on the grounds that it furthers our legitimate interests in commercial activities, such as the following, in ways that are not overridden by the interests or fundamental rights and freedoms of the affected individuals: Providing our Site and Service; Analyzing and improving our business; Communications, including marketing and responding to your inquiries about our services; Addressing information security needs and protecting our Users, Freelance Labs, and others; Managing legal issues.</li>
                <li><strong>To Comply with Legal Obligations.</strong> We need to use and disclose Personal Information in certain ways to comply with our legal obligations.</li>
            </ul>

            <h2>3. Data Retention</h2>
            <p>Freelance Labs retains account and purchase data as long as it is necessary to facilitate a User&apos;s access and use of the Services. When an account is terminated, Personal Information collected will be deleted in accordance with the requirements of applicable law. Personal Information obtained from Site visitors will be maintained as long as it is necessary to provide requested communications and information-based services or until a visitor exercises its right to opt-out of requested communications or information-based services. Anonymized and Pseudo-anonymized data will be retained as long as Freelance Labs determines such data is commercially necessary for its legitimate business interests.</p>

            <h2>4. Information Sharing and Disclosure</h2>
            <p>We may share information about you to provide the Services, for legal and investigative purposes, in connection with sweepstakes and promotions, or if we are part of a merger or acquisition. We may also share non-identifying information with third parties. You have choices as to whether we share your personal information with third parties for their own marketing purposes.</p>
            <p>We may share aggregated Non-Identifying Information and we may otherwise disclose Non-Identifying Information (including, without limitation, Hashed Information) to third parties. We do not share your Personal Information with third parties for those third parties&apos; marketing purposes unless we first provide you with the opportunity to opt-in to or opt-out of such sharing. We may also share the information we have collected about you, including Personal Information, as disclosed at the time you provide your information, with your consent, as otherwise described in this Privacy Policy, or in the following circumstances:</p>
            <ul>
                <li><strong>Information about Freelancers Shared with Clients, Agencies, and Vendors:</strong> We share information regarding Freelancers who have entered into a contract with a Client or who have elected to participate in Freelance Labs, including information in Work Diaries and work history, with Clients, Agencies and vendors. Note that if a Freelancer is suspended from the Freelance Labs Service, we may share that information with Clients for whom that Freelancer has worked or submitted proposals for work. We may also share information with Agencies to whom Freelancers are associated for a particular work project. If you choose to submit a proposal for work as a Freelancer via the Service, we will share information relevant to your application with the applicable Client(s), including, but not limited to, the information contained in your Freelancer Profile.</li>
                <li><strong>Service Providers:</strong> We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services (e.g., without limitation, maintenance services, database management, web analytics and online advertising, payment processing, fraud detection and improvement of Freelance Labs&apos;s features) or to assist us in analyzing how our Service is used. These third parties may have access to your Personal Information in order to perform these tasks on our behalf. SMS information will not be shared without prior consent.</li>
                <li><strong>What Happens If You Agree to Receive Information from Third Parties or Request that We Share Your Information:</strong> You may be presented with an opportunity to receive information and/or marketing offers from one or more third parties. If you agree at that time to have your Personal Information shared, your Personal Information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third party. We are not responsible for the privacy policies and practices of third parties.</li>
                <li><strong>Legal and Investigative Purposes:</strong> Freelance Labs will share information with government agencies as required by law in response to lawful requests by public authorities, including to meet national security or law enforcement requirements and, including without limitation, in connection with reporting earnings. We cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), or, at the request of governmental authorities or other third parties conducting an investigation where we determine in our sole discretion the disclosure is necessary to (a) protect the property and rights of Freelance Labs or a third party, (b) protect the safety of the public or any person, or (c) prevent or stop activity we may consider to be, or pose a risk of being, illegal, fraudulent, unethical or legally actionable activity.</li>
                <li><strong>Internal and Business Transfers:</strong> Freelance Labs may share information, including Personal Information, with its parent company Freelance Labs Inc., and any current or future subsidiaries or affiliates, primarily for business and operational purposes. We may sell, transfer, or otherwise share some or all of our assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets (including, in each case, as part of the due-diligence process with any potential acquiring entity) or in the event of bankruptcy.</li>
                <li><strong>Sweepstakes, Contests, and Promotions:</strong> We may offer sweepstakes, contests, and other promotions (any, a &quot;Promotion&quot;) that may require registration. By participating in a Promotion, you are agreeing to the official rules that govern that Promotion. If you choose to enter a Promotion, your Personal Information may be disclosed to third parties or the public in connection with the administration of such Promotion, including, without limitation, in connection with winner selection, prize fulfillment, and as required by law or permitted by the Promotion&apos;s official rules.</li>
            </ul>

            <h2>5. Third Party Analytics Providers, Ad Servers and Similar Third Parties</h2>
            <p>We may work with advertising agencies and vendors who use technology to help us understand how people use our Site. These vendors may use technologies to serve you advertisements that may interest you. You can choose to opt out of receiving interest-based advertising.</p>
            <p>Freelance Labs works with (or may in the future work with) network advertisers, ad agencies, analytics service providers and other vendors to provide us with information regarding traffic on the Service, including pages viewed and the actions taken when visiting the Service; to serve our advertisements on other web sites, within mobile apps and elsewhere online; and to provide us with information regarding the use of the Service and the effectiveness of our advertisements. Our service providers may collect certain information about your visits to and activity on the Service as well as other websites or services, they may set and access their own tracking technologies on your device (including cookies and web beacons), and may use that information to show you targeted advertisements. Some of these parties may collect Personal Information when you visit the Service or other online websites and services. We may also share certain Non-Identifying Information with these parties, including Hashed Information, in connection with the services they provide to us.</p>
            <p>While we may use a variety of service providers to perform advertising services, some of these companies are members of the Network Advertising Initiative (&quot;NAI&quot;) or the Digital Advertising Alliance (&quot;DAA&quot;) Self-Regulatory Program for Online Behavioral Advertising.</p>
            <p>Freelance Labs uses Google Analytics as a web analytics tool to track user behavior on the Site. Google Analytics collects anonymized information in accordance with their Privacy Policy. However, if you do not want Google Analytics to track your use, you may opt-out by installing Google Analytics Opt-out Browser Add-on.</p>

            <h2>6. Your Choices and Rights</h2>
            <p>You have certain choices regarding how we may communicate with you.</p>
            <p>Registered Freelance Labs Users may update their choices regarding the types of communications you receive from us through your online account. You also may opt-out of receiving marketing emails from us by following the opt-out instructions provided in those emails. Please note that we reserve the right to send you certain communications relating to your account or use of the Service (for example, administrative and service announcements) via email and other means and these transactional account messages may be unaffected if you opt-out from receiving marketing communications. You may opt-out of receiving text messages by replying &quot;STOP&quot; to any text message received. Registered Freelance Labs Users who access the Service by using an Freelance Labs mobile application may, with permission, receive push notifications. Similarly, registered Freelance Labs Users who access the Service by using certain desktop browsers may, with permission, receive push notifications. Notification preferences can be modified in the settings menu for the mobile application or the applicable browser.</p>
            <p>All Users may request access to or correction of any Personal Information we have about them or delete their account and/or request deletion of all Personal Information we have about them. In certain jurisdictions, Users may have certain rights with regard to their Personal Information. We will honor User requests to the extent we can reasonably do so and as required by law. Upon request Freelance Labs will provide you with information about whether we hold any of your personal information. You may access, correct, or request deletion of your personal information by making updates to that information or by contacting Freelance Labs through your online account. If you request to access all personal information you&apos;ve submitted, we will respond to your request to access within 30 days or as otherwise required by applicable law. If you completely delete all such information, then your account may become deactivated. If your account is deactivated or you ask to close your account, you will no longer be able to use the Service.</p>
            <p>Depending on where you are located, you may have certain rights with regard to your Personal Information. If you are located in the European Economic Area (&quot;EEA&quot;), in addition to the rights described above, you may contact us to (1) request a restriction on the processing of your Personal Information, (2) object to the processing of your Personal Information, or (3) exercise other rights with respect to your Personal Information. Freelance Labs uses automated means to calculate the Job Success Score of Freelancers. If you believe that our services have miscalculated your Job Success Score or you would like to exercise any other rights with regard to your Personal Information, please email us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a> for assistance.</p>
            <p>We will use commercially reasonable efforts to honor your requests for deletion; however, certain information will actively persist on the Service even if you close your account, including information in your Work Diaries and messages you posted to the Service. In addition, your Personal Information may remain in our archives and information you update or delete, or information within a closed account, may persist internally for our administrative purposes, to the extent permitted by law. It is not always possible to completely remove or delete information from our databases. In addition, we typically will not remove information you posted publicly through or on the Service. Bear in mind that neither you nor Freelance Labs can delete all copies of information that has been previously shared with others on the Service.</p>

            <h2>7. Security</h2>
            <p>We take a number of steps to protect your data, but no security is guaranteed.</p>
            <p>Freelance Labs takes commercially reasonable steps to help protect and secure the information it collects and stores about Freelance Labs Users. All access to the Site is encrypted using industry-standard transport layer security technology (&quot;TLS&quot;). When you enter sensitive information (such as tax identification number), we encrypt the transmission of that information using secure socket layer technology (&quot;SSL&quot;). We also use HTTP strict transport security to add an additional layer of protection for our Freelance Labs Users. But remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. Thus, while we strive to protect your Personal Information, Freelance Labs cannot ensure and does not warrant the security of any information you transmit to us.</p>

            <h2>8. International Transfer of Personal Information</h2>
            <p>Because we are a U.S. company, we process and store your information in the United States and our service providers may process and store it elsewhere.</p>
            <p>Freelance Labs is a U.S. company. If you are located outside the United States and choose to provide information to us, Freelance Labs transfers Personal Information to the United States for processing, and our service providers may process Personal Information in the United States and elsewhere. These countries may not have the same data protection laws as the country in which you initially provided the information. When we transfer your information to the United States, we will protect it as described in this Privacy Policy.</p>
            <p>When we transfer Personal Information from territories in the EEA or with similar laws to our affiliates or service providers in the United States and elsewhere outside the EEA, we rely on approved data transfer mechanisms, including standard contractual clauses approved by the European Commission and the Privacy Shield. You may request a copy of the standard contractual clauses relevant to your Personal Information, if any, using the contact information below.</p>

            <h2>9. Links to Other Sites</h2>
            <p>Our Service contains links to other websites. If you choose to click on a third party link, you will be directed to that third party&apos;s website. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit Personal Information from you. We encourage you to read the privacy policies or statements of the other websites you visit.</p>

            <h2>10. Public Profile</h2>
            <p>The profile you create on our Site will be publicly accessible unless otherwise indicated. You may change the privacy settings of your profile through your account portal.</p>

            <h2>11. California Residents – Your California Privacy Rights</h2>
            <p>We allow you to choose whether we share your personal information with third parties for their own marketing purposes.</p>
            <p>Pursuant to California Civil Code Section 1798.83, California residents who provide us with personal information in obtaining products or services for personal, family, or household use are entitled to request and obtain from us, one time per calendar year, information about the customer information we shared, if any, with other businesses for their own direct marketing uses. Alternatively, the law provides that a company may comply, as Freelance Labs does, by disclosing in its privacy policy that it provides consumers choice (opt-in or opt-out) regarding sharing Personal Information with third parties for those third parties&apos; direct marketing purposes, and information on how to exercise that choice. As stated above in this Privacy Policy, Freelance Labs provides you choice prior to sharing your personal information with third parties for their direct marketing purposes. If you do not opt-in or if you choose to opt-out at the time Freelance Labs offers that choice, Freelance Labs does not share your information with that identified third party for its direct marketing purposes.</p>
            <p>If you are a California resident and you have questions about our practices with respect to sharing information with third parties for their direct marketing purposes and your ability to exercise choice, please contact us using the contact information below.</p>
            <p>You must put the statement &quot;Your California Privacy Rights&quot; in the subject field of your email or include it in your writing if you choose to write to us at the designated mailing address. You must include your name, street address, city, state, and ZIP code. We will respond to you at your mailing address or, at our option, your email address. We are not responsible for notices that are not labeled or sent properly, or do not have complete information.</p>

            <h2>12. Compliance with the Children&apos;s Online Privacy Protection Act and GDPR Regulations Relating to Children</h2>
            <p>Only persons age 18 or older are authorized to create an account. We do not knowingly collect Personal Information from anyone under the age of 18. If a parent or guardian becomes aware that his or her child (a) under the age of 16 in applicable EU Member Countries, or (b) under the age of 13 in the U.S. and applicable EU Member Countries, has provided us with Personal Data without their consent, he or she should contact <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>. We will delete such Personal Information from our files within a commercially reasonable time, but no later than required under the applicable law relating the child&apos;s country of residence.</p>

            <h2>13. Changes to This Policy</h2>
            <p>We may change this Privacy Policy. If we make material changes, we will provide notice.</p>
            <p>Freelance Labs may update this Privacy Policy at any time and any changes will be effective upon posting. In the event that there are material changes to the way we treat your Personal Information, we will display a notice through the Services prior to the change becoming effective. We may also notify you by email, in our discretion. However, we will use your Personal Information in a manner consistent with the Privacy Policy in effect at the time you submitted the information, unless you consent to the new or revised policy. Express consent to collection and use practices will be obtained when required by applicable law.</p>

            <h2>14. Contacting Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a> or by mail addressed to Freelance Labs, Attn: Legal, PO BOX 471234 San Francisco, CA 94147.</p>

            <hr />

            <h2>GDPR Notice</h2>
            <p><em>Effective March 19, 2019</em></p>
            <p>The General Data Protection Regulation (GDPR) is a change that gives EU residents more clarity and control over how their Personal Information is used. Personal Information is anything that can directly or indirectly identify a person, such as a photo, name, bank details, medical information, computer IP address, and so on. This European-wide law replaces the 1995 Data Protection Directive 95/46/EC.</p>
            <ul>
                <li><strong>Data Controller:</strong> The information that we collect, process and/or use to provide the Services is controlled by Freelance Labs, Inc., Legal, PO BOX 471234 San Francisco, CA 94147. Users may contact us at any time by emailing us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</li>
                <li><strong>Data Processor:</strong> Freelance Labs is the processor of all Freelancer data input by Client and its authorized users, in connection with Client&apos;s use of the Freelance Labs Services.</li>
            </ul>
            <p>We will only collect and process Personal Information where we have lawful bases. Lawful bases include consent (where you have given consent), contract (where processing is necessary for the performance of a contract with you to provide the Services), and &quot;legitimate interests.&quot; Where we rely on your consent to process Personal Information, you have the right to withdraw or decline your consent at any time and where we rely on legitimate interests, you have the right to object. If you have any questions about the lawful bases upon which we collect and use your Personal Information, please contact us at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</p>
            <p><strong>Your Rights:</strong></p>
            <ul>
                <li>Access, review, restrict processing of, or otherwise request erasure of your Personal Information.</li>
                <li>Obtain the identity of the source of any Personal Information collected.</li>
                <li>Request correction of any errors contained within your Personal Information.</li>
                <li>Request transfer of your Personal Information to another service provider.</li>
                <li>Object to the manner in which your Personal Information is processed.</li>
                <li>Lodge a complaint with a supervisory authority.</li>
            </ul>
            <p>Where we rely on your consent to collect Personal Information you may withdraw your consent either through the opt-out links provided in this Privacy Policy or through the contact information contained within this Section.</p>
            <p>For all GDPR-based requests made pursuant to this section, Freelance Labs will (a) respond as required under applicable law, (b) provide a copy of any requested Personal Information in a structured, commonly used and machine-readable format, and (c) transmit such Personal Information to another service provider without restriction in accordance with applicable law.</p>
        </LegalPageLayout>
    );
}
