import type { Metadata } from 'next';
import LegalPageLayout from '@/components/LegalPageLayout';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Terms of Service | Braintrust',
    description: 'Braintrust Marketplace Terms of Service governing the use of the Braintrust talent network platform.',
};

export default function Terms() {
    return (
        <LegalPageLayout title="Braintrust Terms of Service" lastUpdated="February 6, 2025">
            <p><Link href="/air-terms">Click here to go to Braintrust AIR Terms of Service.</Link></p>

            <h2>Introduction</h2>
            <p>Braintrust is a user-controlled, Web3 talent network that connects: (i) clients with freelancers and direct hires (collectively, &quot;Talent&quot;), and (ii) users to each other and their community for career advancement. Braintrust is operated and governed in a decentralized manner by various known entities (&quot;Nodes&quot;) and individual contributors that support, run and govern the Braintrust network. When we refer to &quot;Braintrust&quot; or the &quot;Site Services,&quot; we&apos;re referring collectively and generally to the websites located at www.usebraintrust.com and app.usebraintrust.com (the &quot;Site&quot;), the talent network and all the Nodes that operate Braintrust. More Nodes may be added to support building, operating and governing Braintrust.</p>
            <p>This Terms of Service (also referred to as the &quot;Agreement&quot; or the &quot;Terms&quot;) is a contract between you (&quot;you&quot; or &quot;User&quot;) and Freelance Labs, Inc. (&quot;Talent Node,&quot; &quot;we,&quot; or &quot;us&quot;), the Node that provides access to the Site. Additional third-party Nodes, including Accelerated Labs, Inc. and Distributed Labs, Inc., may provide services for Braintrust&apos;s operation. By using the Site Services, you agree to enter into these Terms with the Talent Node.</p>
            <p><strong>NOTICE ON PROHIBITED USE – RESTRICTED PERSONS:</strong> THE SITE SERVICES ARE NOT OFFERED TO AND MAY NOT BE USED BY:</p>
            <p>PERSONS OR ENTITIES WHO RESIDE IN, ARE CITIZENS OF, ARE LOCATED IN, ARE INCORPORATED IN, OR HAVE A REGISTERED OFFICE IN ANY RESTRICTED TERRITORY, AS DEFINED BELOW (EACH SUCH PERSON OR ENTITY FROM A RESTRICTED TERRITORY, A &quot;RESTRICTED PERSON&quot;).</p>
            <p>WE DO NOT MAKE EXCEPTIONS. THEREFORE, IF YOU ARE A RESTRICTED PERSON, DO NOT ATTEMPT TO USE THE SITE SERVICES. USE OF A VIRTUAL PRIVATE NETWORK (&quot;VPN&quot;) OR ANY OTHER SIMILAR MEANS INTENDED TO CIRCUMVENT THE RESTRICTIONS SET FORTH HEREIN IS PROHIBITED.</p>
            <p><strong>IMPORTANT NOTICE REGARDING ARBITRATION FOR U.S. CUSTOMERS:</strong> WHEN YOU AGREE TO THESE TERMS YOU ARE AGREEING (WITH LIMITED EXCEPTION) TO RESOLVE ANY DISPUTE BETWEEN YOU AND TALENT NODE THROUGH BINDING, INDIVIDUAL ARBITRATION RATHER THAN IN COURT. PLEASE REVIEW CAREFULLY SECTION 28 &quot;DISPUTES BETWEEN YOU AND TALENT NODE&quot; BELOW FOR DETAILS REGARDING ARBITRATION. HOWEVER, IF YOU ARE A RESIDENT OF A JURISDICTION WHERE APPLICABLE LAW PROHIBITS ARBITRATION OF DISPUTES, THE AGREEMENT TO ARBITRATE IN SECTION 28 WILL NOT APPLY TO YOU BUT THE PROVISIONS OF SECTION 27 &quot;GOVERNING LAW AND FORUM CHOICE&quot; WILL APPLY INSTEAD.</p>

            <h2>1. Acceptance of Terms</h2>
            <p>By using our Site Services, you agree to be bound by these Terms. If you do not agree to be bound by these Terms, you are not authorized to use the Site Services. If you are accessing and using the Site Services on behalf of a company (such as your employer) or other legal entity, including an Agency (defined below), you represent and warrant that you have the authority to bind that entity to these Terms. In that case, &quot;you&quot; and &quot;your&quot; will refer to that entity.</p>

            <h2>2. Additional Terms</h2>
            <p>Certain elements of the Site Services may be subject to different terms and conditions or may require you to agree with and accept additional terms and conditions (&quot;Additional Terms&quot;). If there is a conflict between the terms in these Terms and the Additional Terms, then the Additional Terms govern in relation to that element of the Site Services.</p>

            <h2>3. Privacy Policy</h2>
            <p>Please review our Privacy Policy accessible at <Link href="/privacy-policy">www.usebraintrust.com/privacy-policy</Link>, which also governs your use of the Site Services, for information on how we collect, use and share your information.</p>

            <h2>4. Changes to these Terms or the Site Services</h2>
            <p>We may update the Terms from time to time in our sole discretion. If we do, we will let you know by posting the updated Terms on the Site and/or may also send other communications. It is important that you review the Terms whenever we update them or you use the Site Services. If you continue to use the Site Services after we have posted updated Terms, it means that you accept and agree to the changes. If you do not agree to be bound by the changes, you may not use the Site Services anymore. Because our Site Services are evolving over time, we may change or discontinue all or any part of the Site Services, at any time, and without notice, at our sole discretion.</p>

            <h2>5. Who May Use the Site Services</h2>
            <p><strong>(a) Eligibility.</strong> We offer the Site for your business purposes only and not for personal, household, or consumer use. You may use the Site Services only if you: (i) are 18 years or older and capable of forming a binding contract with us; and (ii) are not otherwise barred from using the Site Services under applicable law.</p>
            <p><strong>(b) Compliance.</strong> In order to protect the integrity of the Site Services, we reserve the right, at any time, in our sole discretion, to block access to the Site Services from certain IP addresses and unique device identifiers. For the purposes of the Terms, &quot;Restricted Territory&quot; means Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk People&apos;s Republic and Luhansk People&apos;s Republic regions of Ukraine or any other country to which the United States embargoes goods or imposes similar sanctions.</p>

            <h2>6. Registration of Accounts</h2>
            <p><strong>(a) Access to Site Services.</strong> To access and use certain portions of the Site and the Site Services, you must register for an account (&quot;Account&quot;). We reserve the right to decline a registration to join Braintrust or to register an Account, for any lawful reason, including supply and demand, cost to maintain data, or other business considerations.</p>
            <p><strong>(b) Creating a Profile.</strong> To register for an Account to join the Site, you must complete a User profile (&quot;Profile&quot;), which you consent to be shown to other Users and, unless you change your privacy settings, to the public. You authorize Talent Node, directly or through third parties, to make any inquiries necessary to validate your identity and your location, and confirm your ownership of your email address or financial accounts, subject to applicable law. You agree to provide true, accurate, and complete information on your Profile and all registration and other forms you access on the Site or provide to us and to update your information to maintain its truthfulness, accuracy, and completeness. You agree not to provide any false or misleading information, including information about your identity or location, your business, your skills, or the services your business provides and to correct any such information that is or becomes false or misleading. We reserve the right to revoke the privileges of the Account or access to or use of the Site or Site Services, and those of any and all linked Accounts without warning if, in our sole discretion, false or misleading information has been provided in creating, marketing or maintaining your Profile or Account.</p>
            <p><strong>(c) Account Types.</strong> As described in this Section, there are a number of different Account types. You may create multiple Accounts of different types (i.e., a Client Account and a Talent Account), and you will need to use a unique email address for each separate account. You agree not to have or register for more than one Talent Account without express written permission from us.</p>
            <p>(i) <strong>Freelancer, Agency and Agency Member Account.</strong> Users utilizing the Site to: (A) advertise and provide services to Clients as an independent contractor (each, a &quot;Freelancer&quot;); (B) advertise and provide services to Clients as a team of Freelancers (&quot;Agency&quot;); or (C) advertise their availability for and apply to jobs where Client is seeking to directly hire User as an employee (each, a &quot;Direct Hire&quot;) should, in each case, either register for or add an Account type to use the Site and Site Services as Talent (&quot;Talent Account&quot;). For the avoidance of doubt, an Agency will be considered a Freelancer, and all terms and conditions in the Terms that apply to a Freelancer also apply to an Agency.</p>
            <p>(ii) <strong>Client Account.</strong> A User utilizing the Site to seek and/or obtain services from a Freelancer or a Direct Hire is considered a &quot;Client&quot; and should either register for or add an Account to use the Site and Site Services as a Client (&quot;Client Account&quot;).</p>
            <p><strong>(d) Account Permissions.</strong> You agree not to request or allow another person to create an Account on your behalf, except that an authorized employee or agent may create an Account on behalf of your business. By granting other Users permissions under your Account, you represent and warrant that (i) the User is authorized to act on your behalf, (ii) you are responsible for the User&apos;s actions taken in accordance with those permissions, and (iii) you are fully responsible and liable for any action of any User under your Account.</p>
            <p><strong>(e) Usernames and Passwords.</strong> To protect your Account, keep the account details and password confidential, and notify us right away of any unauthorized use. You&apos;re responsible for all activities that occur under your Account.</p>
            <p><strong>(f) Prohibited User Conduct.</strong> We highly value the integrity of our User community and the Braintrust network. By creating an Account on the Site, you agree to act in good faith and to adhere to the Braintrust <Link href="/code-of-conduct">Code of Conduct</Link> and <Link href="/network-standards">Network Standards</Link>. Users who violate the Code of Conduct or Network Standards may be removed from the Braintrust network and/or permanently banned.</p>

            <h2>7. Users&apos; Relationship with Talent Node</h2>
            <p><strong>(a) User Obligations.</strong> Talent Node merely makes the Site and Site Services available to enable Users to identify and transact directly with each other. Talent Node does not introduce Talent to Clients or find Projects for Talent. The terms between Users with regard to any Project, job proposal submitted by Talent (&quot;Application&quot;) or offer to provide career advice (&quot;Bid&quot; and, together with Project or Application, &quot;User Engagements&quot;) is directly between the Users. Talent Node is not a party to any dealing, contracting and fulfillment of any User Engagement.</p>
            <p>Users are solely responsible for, as applicable: (i) ensuring the accuracy and legality of any User Content, (ii) evaluating any User Engagement and determining the suitability of other Users, (iii) negotiating, agreeing to, and executing any terms or conditions, (iv) performing services pursuant to an User Engagement, or (v) paying for any agreed upon services and any fees associated with the Site Services owed by Client to Talent Node.</p>
            <p>You agree and acknowledge that Talent Node does not make any representations or warranty regarding the truth or accuracy of any listings, the quality or legality of any User Engagement, the qualifications or identities of Users, the ability of Talent to deliver services, or the ability of Clients to pay for services. Talent Node is not responsible for any User Engagement.</p>
            <p><strong>(b) BTRST Token Rewards.</strong> You may receive token rewards in the form of BTRST. In order to receive BTRST rewards, you must first connect a third-party validated digital asset wallet. The <Link href="/btrst-purchaser-terms">Terms of Token Delivery</Link> govern your holdings of BTRST.</p>
            <p><strong>(c) Digital Wallet.</strong> You may participate in the Site Services by linking your digital wallet(s) on supported bridge extensions, which allows you to purchase, store, and engage in transactions using supported digital assets.</p>
            <p><strong>(d) Disclaimers.</strong> WE ARE NOT A BROKER, FINANCIAL INSTITUTION, OR CREDITOR. WE PROVIDE AN ADMINISTRATIVE PLATFORM ONLY. WE FACILITATE TRANSACTIONS BETWEEN USERS BUT ARE NOT A PARTY TO ANY AGREEMENT AMONG ANY USERS. YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE LEGITIMACY AND AUTHENTICITY OF ASSETS YOU TRANSACT WITH THROUGH THE PLATFORM.</p>
            <p><strong>(e) Transactions Are Conducted on the Blockchain.</strong> We do not buy, sell, or take custody or possession of any digital assets for any User, nor do we act as an agent or custodian for any User. We will have no insight into or control over these payments, nor do we have the ability to reverse any payments or transactions.</p>
            <p><strong>(f) Gas Fees.</strong> You agree to pay any applicable fees, including Gas Fees and hosting fees, in connection with transactions on the Site. &quot;Gas Fees&quot; mean the fees that fund the network of computers that run the decentralized blockchain network.</p>
            <p><strong>(g) Taxes.</strong> You are solely responsible for all costs incurred by you in using the Site Services, and for determining, collecting, reporting, and paying all applicable Taxes. You are solely responsible for maintaining all relevant Tax records and complying with any reporting requirements.</p>
            <p><strong>(h) Suspension or Termination.</strong> We may suspend or terminate your access to the Site Services at any time in connection with any transaction as required by applicable law, any governmental authority, or if we determine you are violating these Terms.</p>

            <h2>8. Feedback</h2>
            <p>We appreciate feedback, comments, ideas, proposals and suggestions for improvements to the Site Services (&quot;Feedback&quot;). If you choose to submit Feedback, you agree that we are free to use it without any restriction or compensation to you.</p>

            <h2>9. User Content</h2>
            <p><strong>(a) Posting Content.</strong> Our Site Services may allow you to store or share content such as text, files, documents, graphics, images, music, software, audio and video. Anything (other than Feedback) that you post or otherwise make available through the Site Services is referred to as &quot;User Content&quot;. Talent Node does not claim any ownership rights in any User Content.</p>
            <p><strong>(b) Guidelines for Review and Ratings.</strong> Reviews and ratings of other Users should be truthful, clear, fact-based and helpful to both the recipient and the wider Braintrust community.</p>
            <p><strong>(c) Permissions to Your User Content.</strong> By making any User Content available through the Site Services you hereby grant to Talent Node a non-exclusive, transferable, worldwide, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works based upon, distribute, publicly display, and publicly perform your User Content in connection with operating and providing the Site Services.</p>
            <p><strong>(d) Your Responsibility for User Content.</strong> You are solely responsible for all your User Content. You represent and warrant that you have (and will have) all rights that are necessary to grant us the license rights in your User Content under these Terms.</p>
            <p><strong>(e) Removal of User Content.</strong> You can remove your User Content by specifically deleting it. You should know that in certain instances, some of your User Content may not be completely removed and copies of your User Content may continue to exist on the Site Services.</p>
            <p><strong>(f) Talent Node&apos;s Intellectual Property.</strong> Talent Node grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Site and Site Services. Talent Node and our licensors retain all right, title, and interest in and to all intellectual property rights related in and to the Site and the Site Services.</p>

            <h2>10. Prohibited Uses of the Site</h2>
            <p>You agree not to do any of the following:</p>
            <ul>
                <li>Post, upload, publish, submit or transmit any User Content that: (i) infringes intellectual property rights; (ii) violates any applicable law or regulation; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, or offensive; (v) promotes discrimination, bigotry, racism, hatred, or harassment; (vi) is violent or threatening; or (vii) promotes illegal or harmful activities.</li>
                <li>Use, display, mirror or frame the Site Services without Talent Node&apos;s express written consent.</li>
                <li>Access, tamper with, or use non-public areas of the Site Services or Talent Node&apos;s computer systems.</li>
                <li>Attempt to probe, scan or test the vulnerability of any system or breach any security measures.</li>
                <li>Circumvent any technological measure implemented to protect the Site Services.</li>
                <li>Attempt to access or search the Site Services using any unauthorized engine, software, tool, or mechanism.</li>
                <li>Post or send any unsolicited advertising, promotional materials, junk mail, or spam.</li>
                <li>Forge any TCP/IP packet header or send altered, deceptive or false source-identifying information.</li>
                <li>Attempt to decipher, decompile, disassemble or reverse engineer any software used to provide the Site Services.</li>
                <li>Interfere with the access of any user, host or network.</li>
                <li>Collect or store personally identifiable information from the Site Services from other users without their express permission.</li>
                <li>Share or solicit contact information in a Profile or job posts.</li>
                <li>Impersonate or misrepresent your affiliation with any person or entity.</li>
                <li>Manipulate or misuse the feedback system.</li>
                <li>Duplicate or share accounts, or sell, trade or give an account to another person without consent.</li>
                <li>Take any action to circumvent payment through the Site or any associated fees.</li>
                <li>Use the Site Services in any manner not permitted by these Terms.</li>
                <li>Violate any applicable law or regulation.</li>
                <li>Encourage or enable any other individual to do any of the foregoing.</li>
            </ul>

            <h2>11. Enforcement</h2>
            <p>Talent Node is not obligated to monitor access to or use of the Site Services or to review or edit any content. However, we have the right to do so for the purpose of operating the Site Services, to ensure compliance with these Terms and to comply with applicable law. We reserve the right, but are not obligated, to remove or disable access to any content at any time and without notice. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>

            <h2>12. DMCA/Copyright Policy</h2>
            <p>Talent Node respects copyright law and expects its users to do the same. It is Talent Node&apos;s policy to terminate in appropriate circumstances account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.</p>

            <h2>13. Third-Party Links and Resources</h2>
            <p>The Site Services may allow you to access third-party websites or other resources (collectively, &quot;Third-Party Services&quot;). We provide access only as a convenience and are not responsible for the content, functionality, security, products or services on or available from Third-Party Services. You acknowledge sole responsibility for and assume all risk arising from your use of any Third-Party Services.</p>

            <h2>14. Contractual Relationship Between Users</h2>
            <p><strong>(a) Client and Freelancer Project Terms.</strong> If a Client and Freelancer decide to enter into a Project, the Project is a contractual relationship directly between the Client and Freelancer. Client and Freelancer have complete discretion both regarding whether to enter into a Project with each other and regarding the terms of any Project. You acknowledge and agree that Talent Node is not a party to any Project.</p>
            <p>Clients and Freelancers may enter into any written agreements that they deem appropriate (&quot;Service Contracts&quot;), provided that any such agreements do not conflict with Talent Node&apos;s rights and obligations under these Terms.</p>
            <p><strong>Termination:</strong> Projects are expected to last from the start date (&quot;Start Date&quot;) to the end date (&quot;End Date&quot;) specified in the Offer.</p>
            <p><strong>Termination for Performance:</strong> Client can end the Project before the End Date immediately or at a defined future date as required by Project needs for performance.</p>
            <p><strong>Termination for Convenience:</strong> Client and Freelancer can end the Project before the End Date by providing at least a 2-week notice to the other Party (or the minimum legal notice in their jurisdiction) and by notifying the other Party and Braintrust in writing.</p>
            <p><strong>Written Termination:</strong> Clients must provide written notice to Braintrust to terminate a contract with a Talent. Until Braintrust receives and confirms this notice, the Client remains responsible for all invoices related to the Talent&apos;s work. If the Client terminates the engagement without prior written notice, the Client remains liable for all logged and invoiced hours until formal notification is provided to Braintrust.</p>
            <p><strong>(b) Disputes Among Users.</strong> For disputes arising among Users, you agree to address such dispute directly with such Users and to abide by the dispute process. You acknowledge and agree that Talent Node is not a party to any relationship between any Users or to any User Engagement.</p>

            <h2>15. Default Terms Between Client and Freelancer</h2>
            <p>Unless otherwise agreed upon, the following terms (&quot;Default Terms&quot;) shall apply to transactions between Clients and Freelancers. However, to the extent that there is a conflict between the Service Contracts and the Default Terms, the Service Contracts shall prevail.</p>
            <p><strong>(a) Freelancer&apos;s Representations.</strong> Freelancer represents that Freelancer has the qualifications and ability to perform the Services in a professional manner, without the advice, control, or supervision of Client or Talent Node.</p>
            <p><strong>(b) Non-Exclusive Relationship.</strong> These Terms are non-exclusive. Freelancer shall have the right to perform work for others during the term of these Terms.</p>
            <p><strong>(c) Definition of Intellectual Property Right.</strong> &quot;Intellectual Property Right&quot; means all right, title and interest in and to copyright, rights in databases, patents, trademarks, service marks, design rights, logos, rights in goodwill, compilations, inventions, know-how, confidential information, trade secrets, trade names, business names and domain names together with any similar rights as may exist from time to time anywhere in the world.</p>
            <p><strong>(d) Pre-Existing Intellectual Property.</strong> All Client and Freelancer Intellectual Property Rights existing before the date of these Terms shall remain the property of Client and its affiliates or Freelancer, as applicable.</p>
            <p><strong>(e) Assignment of Work Product.</strong> All inventions, discoveries, trade secrets, designs and improvements thereto, including but not limited to photographs, video, reports, designs, computer programs, systems designs, work notes, program plans, specifications, project analysis, programming code and related documentation, or any other work of authorship conceived, created or made by Freelancer for Client in the performance of services hereunder (&quot;Work Product&quot;) are the sole and exclusive property of Client. Freelancer hereby assigns all rights, title and interest, including but not limited to copyright, in and to such Work Product to Client.</p>
            <p><strong>(f) License in Work Product.</strong> To the extent licensed rights are required, Freelancer grants or shall cause to be granted to Client a fully-paid, irrevocable, royalty-free, worldwide, non-exclusive license in perpetuity.</p>
            <p><strong>(g) Further Assurances.</strong> Freelancer shall take such action as is necessary to assure that none of the material it uses or prepares will violate or infringe upon any right of any person, corporation or other legal entity.</p>
            <p><strong>(h) Definition of Confidential Information.</strong> &quot;Confidential Information&quot; includes, but is not limited to, all information and documents disclosed by or on behalf of one party, whether written or oral, including specifications, drawings, algorithms, technical or business information, research and development, production processes, costs, profit information, client lists, and business plans.</p>
            <p><strong>(i) Confidentiality Obligations.</strong> Both parties agree to hold Confidential Information in strict confidence, not to disclose it to third parties or to use it other than as permitted under these Terms. The obligations shall remain in effect during the term of the Agreement and for two (2) years thereafter, but such obligation will not expire for trade secrets under applicable law.</p>
            <p><strong>(j) Confidentiality Exceptions.</strong> Information will not be considered Confidential if: (i) it has been made publicly available; (ii) it has been rightfully received from a third party; (iii) it has been independently developed; (iv) it was known prior to receipt; (v) it is disclosed without restriction marking; or (vi) it is disclosed pursuant to a court order.</p>
            <p><strong>(k) Compliance with Law.</strong> Client and Freelancer agree to comply with all applicable current and future laws, orders, rules, ordinances, regulations, codes and legal requirements. Each party agrees to defend, indemnify, and hold the other party harmless for claims arising out of the indemnifying party&apos;s violation of such laws.</p>

            <h2>16. Client Obligations and Worker Classification</h2>
            <p><strong>(a) Recordkeeping.</strong> Client will keep true, complete, accurate, and up to date books and records related to documentation evidencing the employment or contractual relationship with Freelancers and Direct Hires, as applicable, and the fulfillment of the labor and social security obligations thereof.</p>
            <p><strong>(b) No Employment Relationship.</strong> Nothing in these Terms is intended to or should be construed to create a partnership, joint venture, franchisor/franchisee or employer-employee relationship between Talent Node and a User. Client is solely responsible for and has complete discretion regarding the selection of any Freelancer or Direct Hire for any Project. Client is solely responsible, warrants its decisions regarding classification are correct, and assumes all liability, for: (i) determining whether Freelancers should be engaged as independent contractors or employees of Client and (ii) determining whether Direct Hires should be engaged as exempt or non-exempt employees of Client. Talent Node will have no input into, or involvement in, worker classification.</p>
            <p><strong>(c) Indemnification.</strong> Client will defend, indemnify and hold Talent Node harmless from and against all claims, damages, liabilities, losses, expenses and costs arising out of or resulting from any action by a Freelancer or Direct Hire against Talent Node that is based on or related to employment classification.</p>

            <h2>17. Non-Circumvention</h2>
            <p><strong>(a) Client Non-Circumvention.</strong> During the period in which Client uses the Site Services and for twelve (12) months thereafter, Client will not, directly or indirectly, encourage or solicit to hire, or otherwise hire or engage for performance of services any Talent of Talent Node who Client discovered in connection with these Terms or the Braintrust network. Client also agrees that it will not refer such Talent directly to subsidiaries, parent companies, partnerships, holdings or investors related to Client in any form without processing such requests through Talent Node.</p>
            <p><strong>(b) Talent Non-Circumvention.</strong> In consideration of the significant time, effort and investment expended in enrolling Talent in the Braintrust talent network and finding Clients for Talent, Talent agrees that during the period over which it provides any Freelancer Services or Bids and for twelve (12) months after any Freelancer Services are completed, Talent will not enter into an employment or consulting relationship with or otherwise engage with any Client that Talent discovered or was referred to in connection with Braintrust without first notifying Talent Node in writing and obtaining prior written consent. In the event of any breach, Talent may be removed from the Braintrust network and permanently banned.</p>

            <h2>18. Referrals and Rewards</h2>
            <p><strong>(a) Connector Program.</strong> Through the Braintrust Connector Program, Users may refer Talent or Clients, which Talent Node may or may not accept in its sole discretion. We may change or terminate the Braintrust Connector Program or a User&apos;s ability to participate at any time for any reason.</p>
            <p><strong>(b) Other Rewards.</strong> Visit the &quot;Earn&quot; page from your profile at www.app.usebraintrust.com for the latest rewards.</p>

            <h2>19. Professional, Career Help Content and Service</h2>
            <p>Braintrust enables individuals to get career help from the community and directly from other community members by connecting Users providing information and advice (&quot;Answerers&quot;) with users seeking information and advice (&quot;Askers&quot;) through a professional network (&quot;Professional Network&quot;).</p>

            <h2>20. Records of Compliance</h2>
            <p>Users will each (a) create and maintain records to document satisfaction of their respective obligations under these Terms, including payment obligations and compliance with tax and employment laws, and (b) provide copies of such records to Talent Node upon request. You are solely responsible for creation, storage, and backup of your business records.</p>

            <h2>21. Warranty Disclaimers</h2>
            <p>THE SITE SERVICES, ANY CONTENT CONTAINED THEREIN, ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. TALENT NODE (AND ITS SUPPLIERS) MAKE NO WARRANTY THAT THE SITE SERVICES: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; (C) WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE.</p>
            <p>TALENT NODE DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, TITLE OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. WE FURTHER EXPRESSLY DISCLAIM ALL LIABILITY OR RESPONSIBILITY IN CONNECTION WITH THIRD-PARTY SERVICES.</p>
            <p>TALENT NODE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY.</p>
            <p>TALENT NODE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR ANY LOSSES, DAMAGES, OR CLAIMS ARISING FROM: (I) USER ERROR SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED WALLET ADDRESSES; (II) SERVER FAILURE OR DATA LOSS; (III) BLOCKCHAIN NETWORKS, DIGITAL WALLETS, OR CORRUPT FILES; (IV) UNAUTHORIZED ACCESS TO SERVICES; OR (V) ANY THIRD PARTY ACTIVITIES.</p>

            <h2>22. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER TALENT NODE NOR ITS SERVICE PROVIDERS WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SITE SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SITE SERVICES.</p>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL TALENT NODE&apos;S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS EXCEED THE AMOUNTS YOU HAVE PAID OR ARE PAYABLE BY YOU TO TALENT NODE FOR USE OF THE SITE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO TALENT NODE, AS APPLICABLE.</p>
            <p>THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN TALENT NODE AND YOU.</p>

            <h2>23. Assumption of Risk</h2>
            <p>You accept, acknowledge, and assume the following risks:</p>
            <ul>
                <li>You are solely responsible for determining what, if any, Site Service Fees, Taxes and Gas Fees apply to your transactions.</li>
                <li>Transactions in digital assets may be irreversible, and losses due to fraudulent or accidental transactions may not be recoverable.</li>
                <li>The regulatory regime governing blockchain technologies, digital assets, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Site Services and the utility of BTRST.</li>
                <li>There are risks associated with using Internet based digital assets, including the risk of hardware, software, and Internet connection issues, malicious software, and unauthorized third-party access.</li>
                <li>A lack of use or public interest in distributed ecosystems could negatively impact the potential utility or value of any digital assets.</li>
                <li>Blockchain systems may have vulnerabilities or other failures. We are not responsible for any issues with the blockchains, including forks, technical node issues, or any other issues that may result in fund losses.</li>
            </ul>

            <h2>24. Indemnification</h2>
            <p>You will indemnify and hold Talent Node and its respective officers, directors, employees and agents, harmless from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Site Services, (b) your use of Third-Party Services, (c) your User Content, or (d) your violation of these Terms.</p>

            <h2>25. Release</h2>
            <p>In addition to the recognition that Talent Node is not a party to any contract between Users, you hereby release Talent Node, our affiliates, and our respective officers, directors, agents, subsidiaries, joint ventures, employees and service providers from claims, demands, and damages of every kind and nature, known and unknown, arising out of or in any way connected with any dispute you have with another User.</p>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU HEREBY WAIVE THE PROTECTIONS OF CALIFORNIA CIVIL CODE § 1542 (AND ANY ANALOGOUS LAW IN ANY OTHER APPLICABLE JURISDICTION) WHICH SAYS: &quot;A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.&quot;</p>

            <h2>26. Termination</h2>
            <p>We may suspend or terminate your access to and use of the Site Services, including suspending access to or terminating your account, at our sole discretion, at any time and without notice to you. You may cancel your account at any time by sending us an email at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>. Upon any termination, discontinuation or cancellation, Sections that by their nature are intended to survive will survive, including Sections: 5-7, 9(a)-9(e), 10-14, 15(c)-15(k), 16-18, and 20-29. Furthermore, any termination shall not terminate any open Service Contract, User Engagement or any related agreements thereunder entered into between Users.</p>

            <h2>27. Governing Law and Forum Choice</h2>
            <p>These Terms and any action related thereto will be governed by the U.S. Federal Arbitration Act, federal arbitration law, and the laws of the State of Delaware, without regard to its conflict of laws provisions. Except as otherwise expressly set forth in Section 28, the exclusive jurisdiction for all Disputes that you and Talent Node are not required to arbitrate will be the state and federal courts located in the County of New Castle, Delaware, and you and Talent Node each waive any objection to jurisdiction and venue in such courts.</p>

            <h2>28. Disputes Between You and Talent Node</h2>
            <p><strong>(a) Mandatory Arbitration of Disputes.</strong> We each agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Site Services (collectively, &quot;Disputes&quot;) will be resolved solely by binding, individual arbitration and not in a class, representative or consolidated action or proceeding. You and Talent Node agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of these Terms, and that you and Talent Node are each waiving the right to a trial by jury or to participate in a class action.</p>
            <p><strong>(b) Exceptions.</strong> As limited exceptions: (i) we both may seek to resolve a Dispute in small claims court if it qualifies; and (ii) we each retain the right to seek injunctive or other equitable relief from a court to prevent the infringement or misappropriation of our intellectual property rights.</p>
            <p><strong>(c) Conducting Arbitration and Arbitration Rules.</strong> The arbitration will be conducted by the American Arbitration Association (&quot;AAA&quot;) under its Consumer Arbitration Rules then in effect. Any arbitration hearings will take place in the county (or parish) where you live, unless we both agree to a different location.</p>
            <p><strong>(d) Arbitration Costs.</strong> Payment of all filing, administration and arbitrator fees will be governed by the AAA Rules. If we prevail in arbitration we&apos;ll pay all of our attorneys&apos; fees and costs and won&apos;t seek to recover them from you. If you prevail in arbitration you will be entitled to an award of attorneys&apos; fees and expenses to the extent provided under applicable law.</p>
            <p><strong>(e) Injunctive and Declaratory Relief.</strong> The arbitrator shall determine all issues of liability on the merits and may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party&apos;s individual claim.</p>
            <p><strong>(f) Class Action Waiver.</strong> YOU AND TALENT NODE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. If this specific provision is found to be unenforceable, then the entirety of this Section 28 shall be null and void.</p>
            <p><strong>(g) Severability.</strong> With the exception of Section 28(f) (&quot;Class Action Waiver&quot;), if an arbitrator or court of competent jurisdiction decides that any part of these Terms is invalid or unenforceable, the other parts will still apply.</p>

            <h2>29. General</h2>
            <p><strong>(a) Entire Agreement.</strong> These Terms along with any applicable Additional Terms constitute the entire and exclusive understanding and agreement between Talent Node and you regarding the Site Services. If any provision is held invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions will remain in full force and effect.</p>
            <p><strong>(b) Reservation of Rights.</strong> Talent Node and its licensors exclusively own all right, title and interest in and to the Site Services, including all associated intellectual property rights. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices.</p>
            <p><strong>(c) Modifications; Waiver.</strong> Talent Node&apos;s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision.</p>
            <p><strong>(d) Assignability.</strong> Except where provided by applicable law in your jurisdiction, you may not assign or transfer these Terms without Talent Node&apos;s prior written consent. Talent Node may freely assign or transfer these Terms without restriction.</p>
            <p><strong>(e) Force Majeure.</strong> The parties will not be responsible for the failure to perform or any delay in performance of any obligation due to labor disturbances, accidents, fires, floods, telecommunications or Internet failures, denial of service attacks, strikes, wars, riots, rebellions, blockades, acts of government, or any other similar conditions beyond the reasonable control of such party.</p>
            <p><strong>(f) Prevailing Language and Location.</strong> The English language version of the Terms will be controlling in all respects and will prevail in case of any inconsistencies with translated versions, if any. The Site is controlled and operated from our facilities in the United States.</p>
            <p><strong>(g) Access of the Site Outside the United States.</strong> Talent Node makes no representations that the Site is appropriate or available for use outside of the United States. Those who access or use the Site from other jurisdictions do so at their own risk and are entirely responsible for compliance with all applicable laws and regulations. You must not directly or indirectly sell, export, re-export, transfer, divert, or otherwise dispose of any software or service to any end user without obtaining any and all required authorizations from the appropriate government authorities.</p>
            <p>In order to access or use the Site or Site Services, you must and hereby represent that you are not: (i) a citizen or resident of a geographic area in which access to the Site is prohibited by applicable law; (ii) a citizen or resident of, or located in, a Restricted Territory; or (iii) an individual identified on the U.S. Department of Commerce Denied Persons or Entity List, the U.S. Department of Treasury Specially Designated Nationals or Blocked Persons Lists, or the U.S. Department of State Debarred Parties List.</p>
            <p><strong>(h) Consent to Use Electronic Records.</strong> In connection with the Terms, you give us permission to provide records to you electronically instead of in paper form.</p>
            <p><strong>(i) Notices.</strong> Any notices or other communications provided by Talent Node under these Terms will be given: (i) via email; or (ii) by posting to the Site Services.</p>
            <p><strong>(j) Questions; Reporting and Correcting Violations.</strong> If you have any questions about the Terms or the Site Services, please contact <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>. If you become aware of any violation of these Terms, you must immediately report it to Customer Service at <a href="mailto:legal@usebraintrust.com">legal@usebraintrust.com</a>.</p>
        </LegalPageLayout>
    );
}
